services:
  mongodbexercise:
    image: mongodbexercise
    build:
      context: .
      dockerfile: Dockerfile

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"